### ISSUE TITLE
[Feature] Collection Level Reporting

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-testops#18]
https://katalon.zendesk.com/agent/tickets/123

1. We need reporting at collection level in Katalon Analytics to look whole run health. 
2. Need collection level report - header fields to show as like in attached screenshot. 
3. Trend/History report at collection level. 
4. E-mail configuration in Katalon Analytics to send test collection level report to user/alias as soon as test run completes. 
5. Ability to choose test collection (or) specific suite from existing test runs and send as an e-mail from Katalon Analytics. 
6. Ability to filter common (or) Unique tests failures from multiple test collection or suite level. Should support to send filtered results in e-mail as well.

**Comment by huongttnguyen** [comment]
This feature is upvoted by Taylor from Katalon forum as well. 

https://forum.katalon.com/t/averages-and-trends/10872

**Comment by huongttnguyen** [comment]
US1: As a Katalon Analytics user, I want to view test reports as a collection level so that I can monitor the whole run health. 

**Acceptance Criteria**
Given a Katalon Analytics project has been integrated with Katalon Studio and Test Suite Collection has been executed
When I observe the execution results on Katalon Analytics
Then I should see the following reports on project / collection level
1. All Test Suite Collections
2. Test Suite Collection details
2.1 Status (Total Failed / Passed / Error / Incomplete) by test suite collection execution (?)
2.2 Performance by test suite collection execution (?)
2.3 History (All test suite executions within collection(?) )

Ref: Latest Single Test Collection Execution Report (without collection name) 
![image](https://user-images.githubusercontent.com/47766596/54113094-23161900-441a-11e9-9ab5-4c81c032b9fe.png)
![image](https://user-images.githubusercontent.com/47766596/54113107-30330800-441a-11e9-8cd4-ff98948af54d.png)

Ref: Current Test Suite Report
![image](https://user-images.githubusercontent.com/47766596/54110385-d7f90780-4413-11e9-9833-9340262d8196.png)
